### ISSUE TITLE
Падает при отправке платежа

### ISSUE THREAD

**Issue by tridetch** [cloudpayments/CloudPayments_AndroidSDKDemo#7]
` 09-28 20:51:43.553 28878-28941/ru.cloudpayments.sdk.demo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                           Process: ru.cloudpayments.sdk.demo, PID: 28878
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                            Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codehaus/jackson/map/ObjectMapper;
                                                                               at ru.cloudpayments.sdk.business.connector.billing.BillingConnector.pay(BillingConnector.java:60)
                                                                               at ru.cloudpayments.sdk.business.connector.billing.BillingConnector.charge(BillingConnector.java:30)
                                                                               at ru.cloudpayments.sdk.view.PayChargeTask.doInBackground(PayChargeTask.java:107)
                                                                               at ru.cloudpayments.sdk.view.PayChargeTask.doInBackground(PayChargeTask.java:49)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                               at java.lang.Thread.run(Thread.java:761) 
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codehaus.jackson.map.ObjectMapper" on path: DexPathList[[zip file "/data/app/ru.cloudpayments.sdk.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.cloudpayments.sdk.demo-1/lib/x86, /system/lib, /vendor/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                               at ru.cloudpayments.sdk.business.connector.billing.BillingConnector.pay(BillingConnector.java:60) 
                                                                               at ru.cloudpayments.sdk.business.connector.billing.BillingConnector.charge(BillingConnector.java:30) 
                                                                               at ru.cloudpayments.sdk.view.PayChargeTask.doInBackground(PayChargeTask.java:107) 
                                                                               at ru.cloudpayments.sdk.view.PayChargeTask.doInBackground(PayChargeTask.java:49) 
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                               at java.lang.Thread.run(Thread.java:761) 
`

**Comment by tridetch** [comment]
Проблема в том что в этом коммите [https://github.com/cloudpayments/CloudPayments_AndroidSDKDemo/commit/29feae14dc08c7d86d30a6e4f8d5601a18043939](url)
убрали из инструкции слова о том что нужно в проекте добавить зависимости для org.codehaus.jackson и сами зависимости из тестового проекта тоже убрали.
В названии коммита также сказано что обновлен sdk cloud payments хотя никааих изменений CloudPayments_AndroidSDK.aar в коммите не видно. Видимо в новой версии sdk не нужны зависимости org.codehaus.jackson, но т.к sdk не обновлен все падает...

**Comment by ign4** [comment]
Добрый день! Файл CloudPayments_AndroidSDK.aar обновлен в этом Вы можете убедиться нажав на ссылку Showing 21 changed files на странице с описанием коммита (https://github.com/cloudpayments/CloudPayments_AndroidSDKDemo/commit/29feae14dc08c7d86d30a6e4f8d5601a18043939), но падение действительно происходит. Разбираемся в чем дело.

**Comment by maximality** [comment]
@ign4 есть новости?

**Comment by ign4** [comment]
Ошибка исправлена, замени у себя в проектах старую версию файла CloudPayments_AndroidSDK.aar на актуальную.
